version: "2.3"

services:
  app:
    image: ibugone/junk-bank-system
    ports: 
      - '3000:3000'
    environment:
      DATABASE_URL: mysql2://junk_bank:junk_bank@db/junk_bank
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: hello
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: junk_bank
      MYSQL_USER: junk_bank
      MYSQL_PASSWORD: junk_bank
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 12
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
