version: "3"

services:
  app:
    image: ibugone/junk-bank-system
    ports: 
      - '3003:3000'
    environment:
      DATABASE_URL: mysql2://junk_bank:junk_bank@db/junk_bank
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: junk_bank
      MYSQL_USER: junk_bank
      MYSQL_PASSWORD: junk_bank
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.3.0/24
